version: '3.7'

networks:
  banco-chn:
    name: banco-chn
    driver: bridge

services:
    frontend:
        container_name: frontend-banco
        image: germanjosepazcordon/frontend-banco
        ports:
            - 80:80
        networks:
          - banco-chn
    
    backend:
        container_name: backend-banco
        image: germanjosepazcordon/backend-banco
        ports:
            - 9000:9000
        networks:
          - banco-chn
